[workspace]
members = [
    "core",
]

[profile.release]
opt-level = 3
lto = "thin"

[profile.release.build-override]
opt-level = 0

[patch.crates-io.tree-sitter]
git = "https://github.com/ubolonton/tree-sitter"
branch = "improve-text-provider"
